[tool.poetry]
name = "ft"
version = "0.1.0"
description = ""
authors = ["subrag <subrag25@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
redis = "^5.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
