name: Build and Commit

on:
  workflow_run:
    workflows: ["Run CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false

    - name: Build
      run: |
        echo "Building"
        go build -o kv-store

